version: '3.9'
services:
  blog-db:
    image: postgres
    container_name: blog-db
    ports:
      - 5432:5432 # Mapping container's internal port 5432 to host port 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aditya@Super
      POSTGRES_DB: nest-blog
    volumes:
      - blog-db-data:/var/lib/postgresql/data # Volume for database persistence
    networks:
      - nestjslearning

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8080:80 # Mapping container's internal port 80 to host port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: aryanshinde6039@gmail.com # Default pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: Adi@123tya # Default pgAdmin login password
    networks:
      - nestjslearning
    depends_on:
      - blog-db # Ensure pgAdmin starts after blog-db

networks:
  nestjslearning:

volumes:
  blog-db-data: # Volume for PostgreSQL persistence
